# This file was generated by GoReleaser. DO NOT EDIT.
cask "parry" do
  version "0.0.5"

  name "parry"
  desc "Runtime security enforcement for AI agents and coding tools"
  homepage "https://github.com/kkd16/parry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "parry"

  on_macos do
    on_intel do
      sha256 "3cb06ac502c28b332568b75f398958d6cd08076b21456272e6d82bef487555e3"
      url "https://github.com/kkd16/parry/releases/download/v#{version}/parry_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "10a07df05bc11f85b7189e762d670aafed39f2876fdb5b77c2965b4d6fa53f66"
      url "https://github.com/kkd16/parry/releases/download/v#{version}/parry_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c3ee57f7d0aac6066b37160f38e4e82c2125816cb47c28682cc5adf00089a315"
      url "https://github.com/kkd16/parry/releases/download/v#{version}/parry_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2c949919896803cc2fbec18fcef59176bfe4d26e8e34fc477ee40b68d6a5d00a"
      url "https://github.com/kkd16/parry/releases/download/v#{version}/parry_Linux_arm64.tar.gz"
    end
  end

  # No zap stanza required
end
