# This file was generated by GoReleaser. DO NOT EDIT.
cask "parry" do
  version "0.0.15"

  on_macos do
    on_intel do
      sha256 "4b3a3336ab454e14660b9855e955986ee947fe4f34f75d6f94b4d3bb193b3098"
      url "https://github.com/kkd16/parry/releases/download/v#{version}/parry_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e8908a571fdb6bcafb3f97416bae39c523369e804eae5b9553160f35957c114d"
      url "https://github.com/kkd16/parry/releases/download/v#{version}/parry_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "da6fb2cdec168eabf730352214972eda52581718b4e9c865dfd6960c1b370a42"
      url "https://github.com/kkd16/parry/releases/download/v#{version}/parry_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "253d3bfadbff637f360ad74b4d19ab13db6b15b01309530abf62769202abbed9"
      url "https://github.com/kkd16/parry/releases/download/v#{version}/parry_Linux_arm64.tar.gz"
    end
  end

  name "parry"
  desc "Runtime security enforcement for AI agents and coding tools"
  homepage "https://github.com/kkd16/parry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "parry"

  # No zap stanza required
end
