# This file was generated by GoReleaser. DO NOT EDIT.
cask "parry" do
  name "parry"
  desc "Runtime security enforcement for AI agents and coding tools."
  homepage "https://github.com/kkd16/parry"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "parry"

  on_macos do
    on_intel do
      url "https://github.com/kkd16/parry/releases/download/v#{version}/parry_Darwin_x86_64.tar.gz"
      sha256 "95b05fa2aafa1c8b0859c86279fbb5e4c5d2b277ac6103cfbc46391dfb69f456"
    end
    on_arm do
      url "https://github.com/kkd16/parry/releases/download/v#{version}/parry_Darwin_arm64.tar.gz"
      sha256 "8a2dc23664512f91047b55b4654ac410731aacfa70ef886201634e249c1deee3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kkd16/parry/releases/download/v#{version}/parry_Linux_x86_64.tar.gz"
      sha256 "b28c1546edad7b2a2bac8519923fd97345e72203f1576e14087364d9ad39bad6"
    end
    on_arm do
      url "https://github.com/kkd16/parry/releases/download/v#{version}/parry_Linux_arm64.tar.gz"
      sha256 "b2515d2f5fe5bf9bdad3b4e9b2908815926a2c814743e7f6915b42962c69cdcb"
    end
  end

  # No zap stanza required
end
